### ISSUE TITLE
提个建议，建议加上一个提示组件

### ISSUE THREAD

**Issue by mxue12138** [museui/muse-ui#1082]
建议后续加上一个toast提示，http://ask.dcloud.net.cn/m/question/17487例如这个文章里的“加入购物车成功”，因为muse-ui我都找不到一个合适的提示组件，现在muse-ui的toast提示在移动端不太合适，可能会盖住底部或者顶部导航栏

**Comment by myronliu347** [comment]
可以设置muse-ui-toast  的className 属性，调整弹出位置 
```javascript
import Toast from 'muse-ui-toast';
Vue.use(Toast, {
    className: 'custom-toast'
})

```
```css
.custom-toast {
     bottom: 200px
}
```
