### ISSUE TITLE
给点建议:这种粗大的滚动条可以再处理一下,可以变得更美观

### ISSUE THREAD

**Issue by langyuxiansheng** [museui/muse-ui#1187]
![image](https://user-images.githubusercontent.com/29669030/45581207-aec84600-b8cc-11e8-9c8b-5167896ae3db.png)

**Comment by myronliu347** [comment]
```css
html {
  scrollbar-arrow-color:#9194a4;
  scrollbar-face-color:transparent;
  scrollbar-3dlight-color: transparent;
  scrollbar-highlight-color:#fff;
  scrollbar-shadow-color:rgba(0,0,0,.15);
  scrollbar-darkshadow-color: transparent;
  scrollbar-track-color:#fff;
  scrollbar-base-color: rgba(0, 0, 0, .3);
}

html ::-webkit-scrollbar {
  width: 10px;
  background-color: transparent;
}

html ::-webkit-scrollbar-track {
  box-shadow: none;
  background-color: #fff;
}

html ::-webkit-scrollbar-thumb {
  width: 10px;
  border-radius: 10px;
  box-shadow: none;
  background-color: rgba(0, 0, 0, .3);
}

```
