### ISSUE TITLE
自定义主题无法覆盖某些组件的颜色

### ISSUE THREAD

**Issue by lb091188** [museui/muse-ui#1190]
![image](https://user-images.githubusercontent.com/16659166/45991526-dfbc2e00-c0b7-11e8-887f-5c542a33e334.png)

如上图所示，通过在main.js中修改了主题的配色，确实也覆盖了本来的主题色。但是在 mu-chip 组件中发现
修改后的主题色，并未生效。因为有一个权重更高的 选择器

```css
.mu-chip.mu-success-color {
  //权重20
    background-color: #4caf50;
}
```

```css
.mu-success-color {
     #//权重10，通过自定义主题功能修改后的颜色
    background-color: #7ed321;
}
```
