### ISSUE TITLE
button的内容为什么都变成了大写

### ISSUE THREAD

**Issue by elmeet** [museui/muse-ui#1288]
怎么才能让button的内容保持原本的大小写？![image](https://user-images.githubusercontent.com/31975448/50679786-ead01400-103f-11e9-91cb-b064ceaff2c6.png)

**Comment by focusonline** [comment]
遇到同样的问题, 请问如何解决的?

**Comment by myronliu347** [comment]
```css
.mu-button {
    text-transform: none !important;
}
```
