### ISSUE TITLE
mu-list组件toggle-icon箭头问题

### ISSUE THREAD

**Issue by MjolnirChen** [museui/muse-ui#1299]
点击展开嵌套列表后toggle-icon没有被加上transform: rotate(180deg)，不知道是组件问题，亦或是需要自行设置？官网样例有效果，但是jsfiddle示例中没有

**Comment by myronliu347** [comment]
```css
.toggle-icon {
  color: @secondaryTextColor;
  transition: transform .3s cubic-bezier(.23,1,.32,1);
  .mu-item__open & {
    transform: rotate(180deg);
  }
}
```
