### ISSUE TITLE
折腾很久，都无法修改默认字体设置。

### ISSUE THREAD

**Issue by gofmt** [museui/muse-ui#35]
很喜欢这套组件，谢谢作者的努力付出！
请教如何设置默认字体？
实际测试修改任何less并不会重新编译muse-ui/dist/muse-ui.css

**Comment by myronliu347** [comment]
在自己的css中重置一下就可以了
确保在 `muse-ui.css` 之后加载

```css
body{
  font-family: sans-serif;
}
```

不过material design 推荐的字体就是 Roboto
