### ISSUE TITLE
Integrate with vue-multiselect

### ISSUE THREAD

**Issue by shijiansu** [museui/muse-ui#366]
The <https://github.com/monterail/vue-multiselect> is a excellent and powerful multiple select Vue UI component, is possible to integrate the MUSE UI with vue-multiselect?

The idea is to wrap the vue-multiselect with muse-ui select, and find a way to override the CSS style of vue-multiselect, its CSS had been operated as __vue-multiselect/dist/vue-multiselect.min.css__, so I guess we can use the same MUSE UI CSS for it. I think it is possible to treat it as a muse-ui plugin, any idea?

Looking forward to hear from you!

**Comment by myronliu347** [comment]
I think you can override `vue-muliselect` css

**Comment by shijiansu** [comment]
恩恩, 随后会尝试. 如果Muse UI官方支持这个, 就更加棒了!

**Comment by shijiansu** [comment]
Hi all,

Did some try for it. Simply you just need to not import the vue-multiselect CSS, and override below CSS values,
````css
.multiselect{
    min-height:30px;
}
.multiselect__select{
    min-height:30px;
}
.multiselect__tags{
    padding-top: 2px;
    min-height:30px;
    margin-bottom: 0px;
    border: none;
}
````
But the underline do not yet works as the Muse UI for the blue color animation. It is related to the CSS "focus" or Vue "textFieldUnderline.vue", it requires more time and effort to integrate it as the same as Muse UI.

期望稍后官方可以正式支持改整合, 谢谢!
