### ISSUE TITLE
position:sticky not works when muse-ui.css

### ISSUE THREAD

**Issue by alexey2baranov** [museui/muse-ui#453]
Hello! 
Hire is 2 jsfiddle which demonstrate problem

sticky works
https://jsfiddle.net/alexey_baranov/46LbLx1s/

if you add https://unpkg.com/muse-ui@2.0.2/dist/muse-ui.css sticky not works (same code with muse-ui.css included)
https://jsfiddle.net/alexey_baranov/310sjcpr/4/

Thanks!

**Comment by myronliu347** [comment]
I find out why

```css
body, html {
    overflow-x: hidden;
    overflow-y: auto;
}
```

**Comment by alexey2baranov** [comment]
@myronliu347 
what is our way if we have to use stiky position?

**Comment by myronliu347** [comment]
You can add reset css 
```css
body, html {
    overflow: visible;
}
```
