### ISSUE TITLE
怎么让高度等于屏幕高度

### ISSUE THREAD

**Issue by acodercat** [museui/muse-ui#504]

**Comment by myronliu347** [comment]
```css
.demo {
position: fixed;
left: 0;
right: 0;
top: 0;
bottom: 0;
}
```
