### ISSUE TITLE
下拉刷新组件,下拉过程中会触发mu-list-item的水波纹效果，如何禁止掉

### ISSUE THREAD

**Issue by love-peach** [museui/muse-ui#521]
```html
<div class="min-music-wrap">
    <mu-refresh-control :refreshing="refreshing" :trigger="trigger" @refresh="refresh"/>
    <mu-list>
       <mu-list-item v-for="(item, index) in optionList" :key="index">
          <span>demo</span>
       </mu-list-item>
    </mu-list>
</div>
```
```less
.min-music-wrap {
  top: 0;
  position: absolute;
  bottom: 0;
  width: 100%;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  overflow-scrolling: touch;
  user-select: none;
}
```
