### ISSUE TITLE
How to put floating action button (FAB) at right bottom of screen?

### ISSUE THREAD

**Issue by ghprod** [museui/muse-ui#66]
Hi, 

This is my approach ..

```css
  .fab-bottom-right {
    position: fixed;
    bottom: 60px;
    right: 60px;
  }
```

```html
<mu-float-button icon="add" mini class="fab-bottom-right" href="#/polyclinics/create"/>
```

Am i doing right? or maybe there's a better method?

Thanks
