### ISSUE TITLE
List custom style not working

### ISSUE THREAD

**Issue by xu6148152** [museui/muse-ui#763]
As `<mu-list-item>` component, if `slot="left"`，container will auto have `padding-left` style。How to modify this style?

I have used the following code to override style, but not working well.
```
.mu-item.show-left {
    padding-left: 72px;
}
```

**Comment by myronliu347** [comment]
```css
.mu-item.show-left {
    padding-left: 72px !important;
}
```
