### ISSUE TITLE
在slider父级元素上加上定位属性会导致拖动定位异常

### ISSUE THREAD

**Issue by ccchangkong** [museui/muse-ui#84]
![111](https://cloud.githubusercontent.com/assets/13186101/20591393/4581bd78-b263-11e6-9543-2cdf29db7f8d.gif)
相关代码
```css
 #app { 
 	width: 1200px;
 	margin: auto;
 	box-shadow: 0 0 5px #333;
        position: relative;
        background-color: #333;
 }
```
```html
<div id="app">
	<mu-slider v-model="value1" :step="5" class="demo-slider"/>
</div>
```
在本例中，#app如果有pr,pa,fixed,那么slider 的小圆点拖动就会有问题，目测要多拖动父级元素左边距的长度才能拖动
